import 'dart:convert';
import 'dart:typed_data';
import 'package:cryptography/cryptography.dart';
import '../../shared/errors/lipi_error.dart';
import 'secure_key_store.dart';

/// Manages Vault encryption keys and HKDF-based key derivation.
///
/// Follows ADR-0008 Section 19-21 and IMPLEMENTATION-CONTRACT Section 24:
/// - Master Key is 256 bits of high entropy generated by cryptographic RNG.
/// - Vault encryption key is distinct from authentication credentials.
/// - Purpose-specific subkeys (Document Key, Database Key) are derived using HKDF-SHA256.
class VaultKeyStore {
  static const String masterKeyAlias = 'lipi_vault_master_key_v1';
  static const String documentKeyContext = 'lipi_vault_document_encryption_v1';
  static const String databaseKeyContext = 'lipi_vault_database_encryption_v1';

  final SecureKeyStore secureStorage;
  final AesGcm _aes = AesGcm.with256bits();
  final Hkdf _hkdf = Hkdf(hmac: Hmac.sha256(), outputLength: 32);

  VaultKeyStore(this.secureStorage);

  /// Retrieves the existing Master Key or securely generates and stores a new 256-bit key.
  Future<SecretKey> getOrCreateMasterKey() async {
    try {
      final existingBytes = await secureStorage.retrieveKey(masterKeyAlias);
      if (existingBytes != null && existingBytes.length == 32) {
        return SecretKey(existingBytes);
      }

      // Generate 256-bit high-entropy secret key
      final newKey = await _aes.newSecretKey();
      final keyBytes = await newKey.extractBytes();
      await secureStorage.storeKey(masterKeyAlias, Uint8List.fromList(keyBytes));
      return SecretKey(keyBytes);
    } catch (e, st) {
      if (e is LipiError) rethrow;
      throw SecurityError('Failed to get or create Vault Master Key', e, st);
    }
  }

  /// Derives purpose-separated 256-bit Document Encryption Key via HKDF-SHA256.
  Future<SecretKey> deriveDocumentKey([SecretKey? masterKey]) async {
    try {
      final mKey = masterKey ?? await getOrCreateMasterKey();
      final derivedKey = await _hkdf.deriveKey(
        secretKey: mKey,
        info: utf8.encode(documentKeyContext),
      );
      return derivedKey;
    } catch (e, st) {
      if (e is LipiError) rethrow;
      throw SecurityError('Failed to derive Vault Document Key via HKDF', e, st);
    }
  }

  /// Derives purpose-separated 256-bit Database Encryption Key via HKDF-SHA256.
  Future<SecretKey> deriveDatabaseKey([SecretKey? masterKey]) async {
    try {
      final mKey = masterKey ?? await getOrCreateMasterKey();
      final derivedKey = await _hkdf.deriveKey(
        secretKey: mKey,
        info: utf8.encode(databaseKeyContext),
      );
      return derivedKey;
    } catch (e, st) {
      if (e is LipiError) rethrow;
      throw SecurityError('Failed to derive Vault Database Key via HKDF', e, st);
    }
  }

  /// Deletes Vault keys from secure storage (used during reset).
  Future<void> deleteVaultKeys() async {
    await secureStorage.deleteKey(masterKeyAlias);
  }

  /// Checks if Master Key exists in secure storage.
  Future<bool> hasMasterKey() async {
    return await secureStorage.keyExists(masterKeyAlias);
  }
}
